config/routes.rb
Andromeda::Application.routes.draw do
  devise_for :users
  
  resources :clusters do
    collection do
      get 'browse'
    end
    
    resources :posts
  end

  match '/clusters' => 'clusters#index', :as => 'user_root'

  root :to => "home#index"
end

app/models/cluster.rb
class Cluster < ActiveRecord::Base
  belongs_to :user
  has_many :posts
  
  validates_presence_of :name, :description, :user
  
  default_scope :order => 'clusters.created_at DESC'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :cluster
  
  validates_presence_of :url, :title, :description
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :clusters, :dependent => :destroy
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clusters_controller.rb
class ClustersController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :browse]
  
  def show
    @cluster = Cluster.find(params[:id])
    @posts = @cluster.posts
  end
  
  def index
    @clusters = current_user.clusters
  end
  
  def new
    @cluster = Cluster.new
  end
  
  def create
    @cluster = current_user.clusters.build(params[:cluster])
    if @cluster.save
      flash[:notice] = "The cluster was saved successfully."
      redirect_to :action => "index"
    else
      flash[:alert] = "The cluster could not be saved."
      render :action => "new"
    end
  end
  
  def browse
    @clusters = Cluster.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  
  def new
    @cluster = Cluster.find(params[:cluster_id])
    @post = @cluster.posts.build
  end
  
  def create
    @cluster = Cluster.find(params[:cluster_id])
    @post = current_user.posts.build(params[:post])
    @post.cluster = @cluster
    
    if @post.save
      flash[:notice] = "The post was saved successfully."
      redirect_to cluster_path(@cluster)
    else
      flash[:alert] = "The post could not be saved."
      render :action => "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clusters_helper.rb
module ClustersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/clusters/_clusters.html.erb
<% if @clusters.empty? %>
  <p>No clusters.</p>
<% else %>
  <ul>
    <% @clusters.each do |cluster| %>
    <li><%= link_to cluster.name, cluster_path(cluster) %></li>
    <% end %>
  </ul>
<% end %>

app/views/clusters/browse.html.erb
<%= render :partial => 'clusters' %>

app/views/clusters/index.html.erb
<%= link_to "Add Cluster", new_cluster_path %>

<%= render :partial => 'clusters' %>

app/views/clusters/new.html.erb
<div id="container">
  <h2>CREATE YOUR CLUSTER!</h2>
    <div id="create-cluster">
    <%= form_for @cluster do |f| %>
      <%= render "shared/error_messages", :target => @cluster %>

      <p><%= f.label :name, :class => "form-text" %><br />
      <%= f.text_field :name, :class => 'form form-field cluster-name' %></p>
  
      <p><%= f.label :description, :class => "form-text" %><br />
      <%= f.text_area :description, :class => "form" %></p>
  
      <p align="right"><%= f.submit "Create cluster" %></p>
    <% end %>
  </div>
  <div id="single">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla id sapien arcu, sit amet congue leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lectus erat, commodo ullamcorper malesuada ac, blandit id nisi. Pellentesque suscipit neque porta lectus euismod eleifend. Pellentesque elementum dui ac augue dapibus eleifend vel eget nibh. Nam ac tortor purus, a rhoncus augue. Donec adipiscing eros in libero pharetra suscipit. Cras eget laoreet nisl. Praesent varius interdum erat non venenatis. Aliquam rutrum scelerisque metus, et tempus nisl scelerisque nec. Maecenas id sagittis est.</p>
    <p><b>Share content with your friends</b><br>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla id sapien arcu, sit amet congue leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lectus erat, commodo ullamcorper malesuada ac, blandit id nisi. Pellentesque suscipit neque porta lectus euismod eleifend. Pellentesque elementum dui ac augue dapibus eleifend vel eget nibh. Nam ac tortor purus, a rhoncus augue. Donec adipiscing eros in libero pharetra suscipit. Cras eget laoreet nisl. Praesent varius interdum erat non venenatis. Aliquam rutrum scelerisque metus, et tempus nisl scelerisque nec. Maecenas id sagittis est. </p>
  </div>
<div class="clear"></div>
</div>

app/views/clusters/show.html.erb
<h1><%= @cluster.name %></h1>

<p><%= @cluster.description %></p>

<p><%= link_to "Add Post", new_cluster_post_path(@cluster) %></p>

<%= render :partial => 'posts/posts' %>

app/views/home/index.html.erb
<div id="container">
<div id="home">
<h1 class="intro">Welcome to Andromeda</h1>
Mauris commodo enim at turpis mollis interdum. Donec facilisis magna sed lorem rutrum et euismod velit faucibus. Aliquam vitae nibh a erat aliquam commodo sed vestibulum odio. Vestibulum semper, turpis in dapibus vestibulum, risus ante tempus eros, a feugiat lectus ipsum quis lorem. Duis dictum orci sit amet eros malesuada a pretium purus rutrum. Cras consequat risus ultricies dui molestie rutrum. Maecenas quis nisl in velit gravida tincidunt sed et lectus. Pellentesque nunc libero, bibendum id ullamcorper a, vehicula eu nisi. Praesent posuere, elit vitae volutpat imperdiet, diam nibh pulvinar diam, sit amet ornare augue turpis a nunc. Curabitur ut nunc dui.<br><br>Mauris commodo enim at turpis mollis interdum. Donec facilisis magna sed lorem rutrum et euismod velit faucibus. Aliquam vitae nibh a erat aliquam commodo sed vestibulum odio. Vestibulum semper, turpis in dapibus vestibulum, risus ante tempus eros, a feugiat lectus ipsum quis lorem. Duis dictum orci sit amet eros malesuada a pretium purus rutrum. Cras consequat risus ultricies dui molestie rutrum. Maecenas quis nisl in velit gravida tincidunt sed et lectus. Pellentesque nunc libero, bibendum id ullamcorper a, vehicula eu nisi. Praesent posuere, elit vitae volutpat imperdiet, diam nibh pulvinar diam, sit amet ornare augue turpis a nunc. Curabitur ut nunc dui. 
</div>
<div id="sidebar">
  <div id="signup">
  <h2>Join the Galaxy!</h2>
  <%= form_for("user", :url => registration_path("user")) do |f| %>

    <p><%= f.label :email %><br />
    <%= f.text_field :email %></p>

    <p><%= f.label :password %><br />
    <%= f.password_field :password %></p>

    <p><%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %></p>

    <p><%= f.submit "Sign up" %></p>
  <% end %>
  <br>
  Already registered? <%= link_to "Sign in", new_user_session_path %>
   
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
  
  <br><br><br>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur risus nisl, vulputate eu pellentesque id, bibendum nec tellus. Etiam tincidunt scelerisque rutrum. Aenean diam nulla, sollicitudin ac sagittis in, dignissim nec lacus. Integer id metus ipsum.
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Andromeda</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<header>
  <div id="header">
    <div id="logo"><%= link_to "ANDROMEDA", root_path, %></div>
    <div id="topics">Development | Design</div>
    <div id="signin">
      <% if user_signed_in? %>

        <%= current_user.email %>
        |
        <%= link_to "Settings", edit_user_registration_path %>
        |
        <%= link_to "Sign out", destroy_user_session_path %>

      <% else %>

        <%= link_to "Sign in", new_user_session_path %>
        |
        <%= link_to "Sign up", new_user_registration_path %>

      <% end %>
    </div>
  </div>
</header>
<div id="content">  
  <%= yield %>
</div>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<footer></footer>

</body>
</html>

app/views/posts/_posts.html.erb
<% if @posts.empty? %>
  <p>No posts.</p>
<% else %>
  <ul>
    <% @posts.each do |post| %>
    <li><%= post.title %></li>
    <% end %>
  </ul>
<% end %>

app/views/posts/new.html.erb
<%= form_for([@cluster, @post]) do |f| %>
  <%= render "shared/error_messages", :target => @post %>

  <p><%= f.label :url %><br />
  <%= f.text_field :url %></p>
  
  <p><%= f.label :title %><br />
  <%= f.text_field :title %></p>

  <p><%= f.label :description %><br />
  <%= f.text_area :description %></p>

  <p><%= f.submit "Create post" %></p>
<% end %>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>  
<div id="error_explanation">  
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
  
  <ul>  
  <% target.errors.full_messages.each do |msg| %>  
    <li><%= msg %></li>  
  <% end %>  
  </ul>  
</div>  
<% end %>